on:
  push:
    branches:
    - main
  workflow_dispatch:

name: Upload to GCS

env:
  BUCKET_NAME: stk.re

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '21'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
    - uses: actions/checkout@v4

    - name: Download production-ready build files
      uses: actions/download-artifact@v4
      with:
        name: production-files
        path: ./dist

    - name: Display structure of downloaded files
      run: ls -R ./dist

    - name: Setup gloud
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
      with:
        version: latest
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Upload to cloud storage
      uses: GoogleCloudPlatform/github-actions/upload-cloud-storage@0.1.3
      with:
        path: /bin
        destination: ${{ env.BUCKET_NAME }}